language: python
os: osx
python:
  - "2.7"
  - "3.4"
  - "3.6"      # current default Python on Travis CI
  # nightly build
# command to install dependencies
cache: pip
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python cred3.py
